---
all: 
    hosts:
        pxeserver:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_private_key_file: /root/OTUS/Otus_Unit_19_PXE/.vagrant/machines/pxeserver/virtualbox/private_key